'use strict';

const SHIPMENT_STATUS = {
  PENDING: 'PENDING',
  PICKUP: 'PICKUP',
  AT_BRANCH: 'AT_BRANCH',
  IN_TRANSIT: 'IN_TRANSIT',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  FAILED: 'FAILED'
};

module.exports = { SHIPMENT_STATUS };
